# Generated by Django 4.0.6 on 2022-07-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kayak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, choices=[('AZ', 'Azul Kayaks'), ('CB', 'Cobra Kayaks'), ('RT', 'Riot Kayaks'), ('BR', 'Boreal Design')], max_length=20, null=True, verbose_name='Brand')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Material')),
                ('description', models.TextField(verbose_name='Description')),
                ('key_features', models.TextField(blank=True, null=True)),
                ('model_code', models.CharField(max_length=20, verbose_name='Code')),
                ('web_page', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, max_length=50, null=True, verbose_name='Youtube')),
                ('steering', models.CharField(blank=True, choices=[('R', 'Rudder'), ('S', 'Skeg')], max_length=20, null=True, verbose_name='Steering')),
                ('paddling', models.CharField(blank=True, choices=[('S', 'Solo'), ('T', 'Tandem')], max_length=20, null=True, verbose_name='Paddling')),
                ('length', models.CharField(blank=True, max_length=10, null=True, verbose_name='Length')),
                ('width', models.CharField(blank=True, max_length=10, null=True, verbose_name='Width')),
                ('height', models.CharField(blank=True, max_length=10, null=True, verbose_name='Height')),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Weight')),
                ('load_capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Load Capacity')),
                ('outer_cockpit_dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('ideal_paddler_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Paddler Size')),
                ('beluga_skirt_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Beluga Skirt')),
                ('impulse_drive', models.CharField(blank=True, max_length=50, null=True, verbose_name='Impulse Drive')),
                ('is_new', models.BooleanField(blank=True, default=False, null=True, verbose_name='New')),
                ('in_stock', models.BooleanField(blank=True, default=True, null=True, verbose_name='In Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='../static/boat_photos')),
                ('Kayak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.kayak')),
            ],
        ),
    ]
