# Generated by Django 4.0.6 on 2022-07-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kayak',
            fields=[
                ('brand', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Model')),
                ('build', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('model_code', models.CharField(max_length=20, verbose_name='Code')),
                ('web_page', models.URLField(max_length=255, unique=True)),
                ('youtube', models.URLField(max_length=50)),
                ('steering', models.CharField(max_length=20, verbose_name='Steering')),
                ('paddling', models.CharField(max_length=20, verbose_name='Paddling')),
                ('is_new', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('discontinued', models.BooleanField(default=True)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('load_capacity', models.CharField(max_length=7)),
            ],
        ),
    ]
