# Generated by Django 4.0.6 on 2022-07-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_kayak_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='paddling',
            field=models.CharField(choices=[('S', 'Solo'), ('T', 'Tandem')], max_length=20, verbose_name='Paddling'),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='steering',
            field=models.CharField(choices=[('RUDDER', 'Rudder'), ('SKEG', 'Skeg')], max_length=20, verbose_name='Steering'),
        ),
    ]
