# Generated by Django 4.0.6 on 2022-08-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_kayak_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='length',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='width',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Width'),
        ),
    ]
