# Generated by Django 4.0.6 on 2022-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_kayak_paddling_alter_kayak_steering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='brand',
            field=models.CharField(choices=[('AZ', 'Axul Kayaks'), ('CB', 'Cobra Kayaks'), ('RT', 'Riot Kayaks'), ('BR', 'Boreal Design')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='model_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Model'),
        ),
    ]
