# Generated by Django 4.0.6 on 2022-07-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_kayak_brand_alter_kayak_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayak',
            name='discontinued',
        ),
        migrations.AlterField(
            model_name='kayak',
            name='brand',
            field=models.CharField(choices=[('AZ', 'Azul Kayaks'), ('CB', 'Cobra Kayaks'), ('RT', 'Riot Kayaks'), ('BR', 'Boreal Design')], max_length=20),
        ),
    ]
