# Generated by Django 4.0.6 on 2022-08-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_kayak_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='brand',
            field=models.CharField(blank=True, choices=[('AZUL', 'Azul'), ('COBRA', 'Cobra'), ('RIOT', 'Riot'), ('RIOT_SUP', 'Riot SUP'), ('BOREAL', 'Boreal Design')], max_length=20, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='paddling',
            field=models.CharField(blank=True, choices=[('SOLO', 'Solo'), ('TANDEM', 'Tandem')], max_length=20, null=True, verbose_name='Paddling'),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='steering',
            field=models.CharField(blank=True, choices=[('RUDDER', 'Rudder'), ('SKEG', 'Skeg')], max_length=20, null=True, verbose_name='Steering'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='../media/boat_photos'),
        ),
    ]
