# Generated by Django 4.0.6 on 2022-08-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_kayak_brand_alter_kayak_paddling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boats'),
        ),
    ]
