# Generated by Django 4.0.6 on 2022-07-12 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_kayak_beluga_skirt_size_kayak_ideal_paddler_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayak',
            name='key_features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.feature'),
        ),
    ]
