# Generated by Django 4.0.6 on 2022-08-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayak',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
