# Generated by Django 4.0.6 on 2022-07-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_kayak_key_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='key_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
