# Generated by Django 4.0.6 on 2022-08-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_kayak_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='brand',
            field=models.CharField(blank=True, choices=[('AZUL KAYAKS', 'Azul'), ('COBRA KAYAKS', 'Cobra'), ('RIOT KAYAKS', 'Riot'), ('RIOT SUP', 'Riot SUP'), ('BOREAL DESIGN', 'Boreal Design')], max_length=20, null=True, verbose_name='Brand'),
        ),
    ]
