# Generated by Django 4.0.6 on 2022-08-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_kayak_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='brand',
            field=models.CharField(blank=True, choices=[('AZUL KAYAKS', 'Azul kayaks'), ('COBRA KAYAKS', 'Cobra kayaks'), ('RIOT KAYAKS', 'Riot Kayaks'), ('RIOT SUP', 'Riot SUP'), ('BOREAL DESIGN', 'Boreal Design')], max_length=20, null=True, verbose_name='Brand'),
        ),
    ]
