# Generated by Django 4.0.6 on 2022-08-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_alter_kayak_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
