# Generated by Django 4.0.6 on 2022-08-14 19:53

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_alter_kayak_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.Kayak.upload_path),
        ),
    ]
