# Generated by Django 4.0.6 on 2022-08-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_alter_kayak_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='steering',
            field=models.CharField(blank=True, choices=[('RUDDER', 'Rudder'), ('SKEG', 'Skeg'), ('BOTH', 'Both')], max_length=20, null=True, verbose_name='Steering'),
        ),
    ]
