# Generated by Django 4.0.6 on 2022-08-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_alter_kayak_steering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='brand',
            field=models.CharField(choices=[('AZUL KAYAKS', 'Azul kayaks'), ('COBRA KAYAKS', 'Cobra kayaks'), ('RIOT KAYAKS', 'Riot Kayaks'), ('RIOT SUP', 'Riot SUP'), ('BOREAL DESIGN', 'Boreal Design')], default=None, max_length=20, verbose_name='Brand'),
            preserve_default=False,
        ),
    ]
