# Generated by Django 4.0.6 on 2022-08-24 08:31

import catalogue.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_alter_kayak_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayak',
            name='top',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.Kayak.upload_path),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='brand',
            field=models.CharField(choices=[('Azul Kayaks', 'Azul kayaks'), ('Cobra Kayaks', 'Cobra kayaks'), ('Riot Kayaks', 'Riot Kayaks'), ('Riot SUP', 'Riot SUP'), ('Boreal Design', 'Boreal Design')], max_length=20, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='paddling',
            field=models.CharField(blank=True, choices=[('Solo', 'Solo'), ('Tandem', 'Tandem')], max_length=20, null=True, verbose_name='Paddling'),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='steering',
            field=models.CharField(blank=True, choices=[('Rudder', 'Rudder'), ('Skeg', 'Skeg'), ('Both', 'Both')], max_length=20, null=True, verbose_name='Steering'),
        ),
    ]
