# Generated by Django 4.0.6 on 2022-08-24 08:33

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_kayak_top_alter_kayak_brand_alter_kayak_paddling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayak',
            name='top',
        ),
        migrations.AlterField(
            model_name='kayak',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.Kayak.upload_path),
        ),
    ]
