# Generated by Django 4.0.6 on 2022-08-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_rename_photo_path_kayak_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayak',
            name='photo',
        ),
        migrations.AddField(
            model_name='kayak',
            name='action_shot_1',
            field=models.URLField(blank=True, null=True, verbose_name='Action Shot 1'),
        ),
        migrations.AddField(
            model_name='kayak',
            name='action_shot_2',
            field=models.URLField(blank=True, null=True, verbose_name='Action Shot 2'),
        ),
        migrations.AddField(
            model_name='kayak',
            name='angle_view',
            field=models.URLField(blank=True, null=True, verbose_name='Angle View'),
        ),
        migrations.AddField(
            model_name='kayak',
            name='side_view',
            field=models.URLField(blank=True, null=True, verbose_name='Side View'),
        ),
        migrations.AddField(
            model_name='kayak',
            name='top_view',
            field=models.URLField(blank=True, null=True, verbose_name='Top View'),
        ),
    ]
