# Generated by Django 4.0.6 on 2022-08-28 19:05

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_remove_kayak_photo_kayak_action_shot_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='action_shot_1',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.Kayak.upload_path, verbose_name='Action Shot 1'),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='action_shot_2',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.Kayak.upload_path, verbose_name='Action Shot 2'),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='angle_view',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.Kayak.upload_path, verbose_name='Angle View'),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='side_view',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.Kayak.upload_path, verbose_name='Side View'),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='top_view',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.Kayak.upload_path, verbose_name='Top View'),
        ),
    ]
