# Generated by Django 4.0.6 on 2022-12-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_alter_kayak_action_shot_1_alter_kayak_action_shot_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='brand',
            field=models.CharField(choices=[('Azul Kayaks', 'Azul kayaks'), ('Cobra Kayaks', 'Cobra kayaks'), ('Riot Kayaks', 'Riot Kayaks'), ('Riot SUP', 'Riot SUP'), ('Boreal Design', 'Boreal Design')], max_length=50, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='kayak',
            name='model_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code'),
        ),
    ]
